version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    links: 
      - db
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
  db:
    build: ./bin/mysql
    container_name: db
    ports:
      - "3306:3306"
    volumes: 
      - ${DATABASE_DIR-./data}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - /sessions